import type { FeeUnit, PostDetailDto, PostSummaryDto, RentalStatus } from "@/features/post/schemas";

export const POST_CONSTANTS = {};
type RawPostSummary = {
	postId: number;
	title: string;
	imageUrl: string;
	rentalFee: number;
	feeUnit: FeeUnit;
	rentalStatus: RentalStatus;
};

const RAW_POST_SUMMARIES: RawPostSummary[] = [
	{
		postId: 1,
		title: "글 제목 1",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 0,
		feeUnit: "DAY",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 2,
		title: "글 제목 2",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 2000,
		feeUnit: "HOUR",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 3,
		title: "글 제목 3",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 0,
		feeUnit: "DAY",
		rentalStatus: "RENTED_OUT",
	},
	{
		postId: 4,
		title: "글 제목 4",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 4000,
		feeUnit: "HOUR",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 5,
		title: "글 제목 5",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 5000,
		feeUnit: "DAY",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 6,
		title: "글 제목 6",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 6000,
		feeUnit: "HOUR",
		rentalStatus: "RENTED_OUT",
	},
	{
		postId: 7,
		title: "글 제목 7",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 7000,
		feeUnit: "DAY",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 8,
		title: "글 제목 8",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 8000,
		feeUnit: "HOUR",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 9,
		title: "글 제목 9",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 9000,
		feeUnit: "DAY",
		rentalStatus: "RENTED_OUT",
	},
	{
		postId: 10,
		title: "글 제목 10",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 10000,
		feeUnit: "HOUR",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 11,
		title: "글 제목 11",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 11000,
		feeUnit: "DAY",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 12,
		title: "글 제목 12",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 12000,
		feeUnit: "HOUR",
		rentalStatus: "RENTED_OUT",
	},
	{
		postId: 13,
		title: "글 제목 13",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 13000,
		feeUnit: "DAY",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 14,
		title: "글 제목 14",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 14000,
		feeUnit: "HOUR",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 15,
		title: "글 제목 15",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 15000,
		feeUnit: "DAY",
		rentalStatus: "RENTED_OUT",
	},
	{
		postId: 16,
		title: "글 제목 16",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 16000,
		feeUnit: "HOUR",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 17,
		title: "글 제목 17",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 17000,
		feeUnit: "DAY",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 18,
		title: "글 제목 18",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 18000,
		feeUnit: "HOUR",
		rentalStatus: "RENTED_OUT",
	},
	{
		postId: 19,
		title: "글 제목 19",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 19000,
		feeUnit: "DAY",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 20,
		title: "글 제목 20",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 20000,
		feeUnit: "HOUR",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 21,
		title: "글 제목 21",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 21000,
		feeUnit: "DAY",
		rentalStatus: "RENTED_OUT",
	},
	{
		postId: 22,
		title: "글 제목 22",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 22000,
		feeUnit: "HOUR",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 23,
		title: "글 제목 23",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 23000,
		feeUnit: "DAY",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 24,
		title: "글 제목 24",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 24000,
		feeUnit: "HOUR",
		rentalStatus: "RENTED_OUT",
	},
	{
		postId: 25,
		title: "글 제목 25",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 25000,
		feeUnit: "DAY",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 26,
		title: "글 제목 26",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 26000,
		feeUnit: "HOUR",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 27,
		title: "글 제목 27",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 27000,
		feeUnit: "DAY",
		rentalStatus: "RENTED_OUT",
	},
	{
		postId: 28,
		title: "글 제목 28",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 28000,
		feeUnit: "HOUR",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 29,
		title: "글 제목 29",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 29000,
		feeUnit: "DAY",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 30,
		title: "글 제목 30",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 30000,
		feeUnit: "HOUR",
		rentalStatus: "RENTED_OUT",
	},
	{
		postId: 31,
		title: "글 제목 31",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 31000,
		feeUnit: "DAY",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 32,
		title: "글 제목 32",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 32000,
		feeUnit: "HOUR",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 33,
		title: "글 제목 33",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 33000,
		feeUnit: "DAY",
		rentalStatus: "RENTED_OUT",
	},
	{
		postId: 34,
		title: "글 제목 34",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 34000,
		feeUnit: "HOUR",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 35,
		title: "글 제목 35",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 35000,
		feeUnit: "DAY",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 36,
		title: "글 제목 36",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 36000,
		feeUnit: "HOUR",
		rentalStatus: "RENTED_OUT",
	},
	{
		postId: 37,
		title: "글 제목 37",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 37000,
		feeUnit: "DAY",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 38,
		title: "글 제목 38",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 38000,
		feeUnit: "HOUR",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 39,
		title: "글 제목 39",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 39000,
		feeUnit: "DAY",
		rentalStatus: "RENTED_OUT",
	},
	{
		postId: 40,
		title: "글 제목 40",
		imageUrl: "/dummy-post-image.png",
		rentalFee: 40000,
		feeUnit: "HOUR",
		rentalStatus: "AVAILABLE",
	},
];

const POST_DETAIL_DEFAULTS = {
	content:
		"카메라를 대여해드립니다 카메라를 대여해드립니다 카메라를 대여해드립니다 카메라를 대여해드립니다 카메라를 대여해드립니다 카메라를 대여해드립니다 카메라를 대여해드립니다 카메라를 대여해드립니다 카메라를 대여해드립니다 카메라를 대여해드립니다",
	sellerId: 3,
	sellerNickname: "Tester",
	sellerAvatar: "/default-profile.png",
	updatedAt: "2026-01-13T13:30:24.123456Z",
	isSeller: true,
	chatroomId: -1,
	activeChatroomCount: 3,
};

export const DUMMY_POST_SUMMARIES: PostSummaryDto[] = RAW_POST_SUMMARIES.map((post) => ({
	postId: post.postId,
	postTitle: post.title,
	postImageId: post.postId,
	postFirstImageUrl: post.imageUrl,
	rentalFee: post.rentalFee,
	feeUnit: post.feeUnit,
	rentalStatus: post.rentalStatus,
}));

const createImageUrls = (imageUrl: string, seed: number) => ({
	imageInfos: [
		{ postImageId: seed * 10 + 1, imageUrl },
		{ postImageId: seed * 10 + 2, imageUrl },
	],
});

export const DUMMY_POST_DETAIL_BY_ID = new Map<number, PostDetailDto>(
	DUMMY_POST_SUMMARIES.map((post, index) => [
		post.postId,
		{
			title: post.postTitle,
			content: POST_DETAIL_DEFAULTS.content,
			imageUrls: createImageUrls(post.postFirstImageUrl, index + 1),
			sellerId: POST_DETAIL_DEFAULTS.sellerId,
			sellerNickname: POST_DETAIL_DEFAULTS.sellerNickname,
			sellerAvatar: POST_DETAIL_DEFAULTS.sellerAvatar,
			rentalFee: post.rentalFee,
			feeUnit: post.feeUnit,
			rentalStatus: post.rentalStatus,
			updatedAt: POST_DETAIL_DEFAULTS.updatedAt,
			isSeller: POST_DETAIL_DEFAULTS.isSeller,
			chatroomId: POST_DETAIL_DEFAULTS.chatroomId,
			activeChatroomCount: POST_DETAIL_DEFAULTS.activeChatroomCount,
		} satisfies PostDetailDto,
	]),
);
