import z from "zod";

import { PostSchema } from "@/features/post/schemas";

type Post = z.infer<typeof PostSchema>;

export const POST_CONSTANTS = {};
export const DUMMY_POSTS: Post[] = [
	{
		postId: 1,
		postTitle: "글 제목 1",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 0,
		feeUnit: "DAY",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 2,
		postTitle: "글 제목 2",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 2000,
		feeUnit: "HOUR",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 3,
		postTitle: "글 제목 3",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 0,
		feeUnit: "DAY",
		rentalStatus: "RENTED_OUT",
	},
	{
		postId: 4,
		postTitle: "글 제목 4",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 4000,
		feeUnit: "HOUR",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 5,
		postTitle: "글 제목 5",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 5000,
		feeUnit: "DAY",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 6,
		postTitle: "글 제목 6",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 6000,
		feeUnit: "HOUR",
		rentalStatus: "RENTED_OUT",
	},
	{
		postId: 7,
		postTitle: "글 제목 7",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 7000,
		feeUnit: "DAY",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 8,
		postTitle: "글 제목 8",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 8000,
		feeUnit: "HOUR",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 9,
		postTitle: "글 제목 9",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 9000,
		feeUnit: "DAY",
		rentalStatus: "RENTED_OUT",
	},
	{
		postId: 10,
		postTitle: "글 제목 10",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 10000,
		feeUnit: "HOUR",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 11,
		postTitle: "글 제목 11",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 11000,
		feeUnit: "DAY",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 12,
		postTitle: "글 제목 12",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 12000,
		feeUnit: "HOUR",
		rentalStatus: "RENTED_OUT",
	},
	{
		postId: 13,
		postTitle: "글 제목 13",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 13000,
		feeUnit: "DAY",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 14,
		postTitle: "글 제목 14",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 14000,
		feeUnit: "HOUR",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 15,
		postTitle: "글 제목 15",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 15000,
		feeUnit: "DAY",
		rentalStatus: "RENTED_OUT",
	},
	{
		postId: 16,
		postTitle: "글 제목 16",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 16000,
		feeUnit: "HOUR",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 17,
		postTitle: "글 제목 17",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 17000,
		feeUnit: "DAY",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 18,
		postTitle: "글 제목 18",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 18000,
		feeUnit: "HOUR",
		rentalStatus: "RENTED_OUT",
	},
	{
		postId: 19,
		postTitle: "글 제목 19",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 19000,
		feeUnit: "DAY",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 20,
		postTitle: "글 제목 20",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 20000,
		feeUnit: "HOUR",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 21,
		postTitle: "글 제목 21",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 21000,
		feeUnit: "DAY",
		rentalStatus: "RENTED_OUT",
	},
	{
		postId: 22,
		postTitle: "글 제목 22",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 22000,
		feeUnit: "HOUR",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 23,
		postTitle: "글 제목 23",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 23000,
		feeUnit: "DAY",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 24,
		postTitle: "글 제목 24",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 24000,
		feeUnit: "HOUR",
		rentalStatus: "RENTED_OUT",
	},
	{
		postId: 25,
		postTitle: "글 제목 25",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 25000,
		feeUnit: "DAY",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 26,
		postTitle: "글 제목 26",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 26000,
		feeUnit: "HOUR",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 27,
		postTitle: "글 제목 27",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 27000,
		feeUnit: "DAY",
		rentalStatus: "RENTED_OUT",
	},
	{
		postId: 28,
		postTitle: "글 제목 28",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 28000,
		feeUnit: "HOUR",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 29,
		postTitle: "글 제목 29",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 29000,
		feeUnit: "DAY",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 30,
		postTitle: "글 제목 30",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 30000,
		feeUnit: "HOUR",
		rentalStatus: "RENTED_OUT",
	},
	{
		postId: 31,
		postTitle: "글 제목 31",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 31000,
		feeUnit: "DAY",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 32,
		postTitle: "글 제목 32",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 32000,
		feeUnit: "HOUR",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 33,
		postTitle: "글 제목 33",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 33000,
		feeUnit: "DAY",
		rentalStatus: "RENTED_OUT",
	},
	{
		postId: 34,
		postTitle: "글 제목 34",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 34000,
		feeUnit: "HOUR",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 35,
		postTitle: "글 제목 35",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 35000,
		feeUnit: "DAY",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 36,
		postTitle: "글 제목 36",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 36000,
		feeUnit: "HOUR",
		rentalStatus: "RENTED_OUT",
	},
	{
		postId: 37,
		postTitle: "글 제목 37",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 37000,
		feeUnit: "DAY",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 38,
		postTitle: "글 제목 38",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 38000,
		feeUnit: "HOUR",
		rentalStatus: "AVAILABLE",
	},
	{
		postId: 39,
		postTitle: "글 제목 39",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 39000,
		feeUnit: "DAY",
		rentalStatus: "RENTED_OUT",
	},
	{
		postId: 40,
		postTitle: "글 제목 40",
		postFirstImageUrl: "/dummy-post-image.png",
		rentalFee: 40000,
		feeUnit: "HOUR",
		rentalStatus: "AVAILABLE",
	},
];
